language: java
branches:
  only:
  - develop
  - master
notifications:
  email:
    recipients:
    - begona.aramburu@gmail.com
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
before_install:
  - chmod +x mvnw